name: roamusic
favicon: null
layout_spectrum: 0.74707
typography_spectrum: 0.0334
title: 'Rehearsals of Absent Mind '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#252422'
    - '#4f4e4c'
    - '#787775'
    - '#d0cecf'
  brandStrength: 0.75
  lightness: 0.4375
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
