name: ROAMusic
favicon: null
layout_spectrum: 0.74707
typography_spectrum: 0.04008
title: ROAM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#494d56'
    - '#121c16'
    - '#ffffff'
    - '#b6bfb6'
    - '#ad93b7'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
