name: ROAM
favicon: null
layout_spectrum: 0.74707
typography_spectrum: 0.04008
title: ROAM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1e1e'
    - '#454545'
    - '#929292'
    - '#676767'
    - '#cbcbcd'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
