name: ROAMEC
favicon: null
layout_spectrum: 0.9716403388883919
typography_spectrum: 0
title: ENSAYOS DE NO PENSAR
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#221c02'
    - '#44300c'
    - '#514523'
    - '#7a6447'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
