name: ROAMEC
favicon: null
layout_spectrum: 0.89816
typography_spectrum: 0.0384
title: E N S A Y O S  DE  NO  P E N S A R
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#221c02'
    - '#44300c'
    - '#514523'
    - '#7a6447'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
