name: ROAMmusic
favicon: null
layout_spectrum: 1
typography_spectrum: 0.02171
title: 'Rehearsals of Absent Mind '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#221c02'
    - '#44300c'
    - '#514523'
    - '#7a6447'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
