name: ROAM
favicon: null
layout_spectrum: 0.48998
typography_spectrum: 0.0334
title: 'REHEARSALS OF ABSENT MIND '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1e1e'
    - '#454545'
    - '#929292'
    - '#676767'
    - '#cbcbcd'
  brandStrength: 0.625
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
